### ISSUE TITLE
Lost in the middle을 어떻게 해결하려고 할까?

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#11]
이 문제를 해결하려는 후속 연구들 모양은 어떠려나?
1. RAG 파이프라인을 고도화해서 Docs를 쪼갤듯
2. 학습 단계에서 해결
    - [Make Your LLM Fully Utilize the Context](https://arxiv.org/pdf/2404.16811)

<img width="708" alt="image" src="https://github.com/user-attachments/assets/f5eca5b2-806c-4395-a4a7-a4f5409ab785">

<img width="708" alt="image" src="https://github.com/user-attachments/assets/5ef3eb39-b3b1-4f7c-b062-8e5e322312db">

**Comment by ZiminPark** [comment]
[Summary of a Haystack: A Challenge to Long-Context LLMs and RAG Systems](https://arxiv.org/pdf/2407.01370)

<img width="708" alt="image" src="https://github.com/user-attachments/assets/e788c603-6f5d-4fff-b077-c5a2b7bd0853">

**Comment by ZiminPark** [comment]
Found in the Middle: Calibrating Positional Attention Bias
Improves Long Context Utilization

**Comment by realsigridjin** [comment]
생각

- 최근의 LLM은 Long-context에서 매우 강한 모습을 보임
- 원래 LLM은 long-context input에 취약했음(e.g., lost in the middle)
- 그렇지만 이 문제가 알려진 이후 1년 동안 관련한 많은 성과가 있었고, 현재의 LLM은 대단히 긴 context length(gemini pro는 1M 토큰) 를 가지고 있으며, lost-in-the-middle 문제도 많이 해결되었음
- 위 논문의 LC vs RAG 성능 비교 결과가 이렇게 나온 것은 그 이유 같음. 즉, 어지간히 긴 내용의 문서는 그냥 전체를 때려박는 것이 대부분의 경우 성능이 더 좋다는 것

RAG의 오답 유형
- RAG에서 주로 틀리는 유형을 살펴보면 implicit(이건 LC도 잘 못할듯)와 multi-step임
- single turn이 아니라 여러 개의 chunk를 가져와서 내용을 조합하고 추론해야만 답을 얻을 수 -있는 쿼리는 해결하기 힘듬. LC가 이런 영역에서 경쟁력이 있기 때문에 좋은 성능이 나왔다고 생각

리서치 아이디어
- 제 관심은 그래서 RAG는 죽었냐는 것. 결론부터 얘기하면 NO라 생각.
- Chain-of-thought + RAG로 결합해보면 오히려 더 잘할 것 같음
- Chain-of-thought 계열의 방식으로 주어진 쿼리를 해결하기 위해서 풀이 단계를 생성한 후 각 단계별로 필요한경우 RAG를 통해 chunk를 찾아와서 중간 결과를 생성, 다음 단계로 넘어가는 방식
- 질문과 책 한권을 던져주고 알아서 답을 찾으라는 것(LC) 보다는 답을 찾기 위한 풀이 과정을 적게한 후 필요한 부분만 찾아서 참고하면 되므로 현재의 single-turn RAG나 LC 보다도 훨 더 좋을 것 같음

**Comment by jaehc90** [comment]
진형님이 말씀 해주신 부분중 3번쨰 COT 중 Plan and Solve 계열 multi hop을 step by step으로 나누고 step끼리 결론이 나오면 이를 활용하여 다른 step과 결합하는 논문을 본적이 있는데 이것도 결과가 좋았긴 했어요. 이거 어떻게 발전하는지 봐야 겠네요. 

예전에 영수님이 말씀 주신것 처럼 information retrieval (extraction) 과 이를 바탕으로 추론하는 deduction은 둘은 나눠져야 하는게 맞는거 같습니다. multi hop인경우 이번 논문에서 읽은 것(hotpot QA)처럼 어렵고 이를 foundation모델이 해결해줄거 같긴 합니다. 지금은 lost in the middle 문제중 information extraction 문제는 해결되는 성향이 강하긴 한데, 여전히 10% 이후인 초반에 데이터에 대해서는 취약한 경향들이 있긴 한거 같습니다.
