### ISSUE TITLE
Reference for "RAFT"

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#12]
https://platform.openai.com/docs/guides/optimizing-llm-accuracy/llm-optimization-context

**Comment by haconedu** [comment]
![image](https://github.com/user-attachments/assets/387c94db-8ae9-43f7-998a-fd70ddfa0057)
![image](https://github.com/user-attachments/assets/08ab966f-8a09-40f3-8b49-592d390207fb)
