### ISSUE TITLE
"Domain"은 어떻게 정의할 수 있을까?

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#14]
같은 주제의 묶음?

Finite한 문서?

**Comment by ZiminPark** [comment]
"내 회사 데이터" 

라면 주제가 묶여있나? 주제가 묶여있지 않아도 되나?

**Comment by jaehc90** [comment]
Domain? 

> adapting LLMs to the specialized domains (e.g., recent news, enterprise private documents, or program resources
constructed after the training cutoff)

**Comment by ZiminPark** [comment]
Task Specific (요약, 의견서 작성)
Knowledge

**Comment by jaehc90** [comment]
Domain Specific vs Task Specific. 

- Task => 업무에 관한 것

**Comment by ZiminPark** [comment]
**은행용어** 
시설자금?
운전대? -> GPT3.5 handle, 은행 용어 따로 있음.

**Comment by jaehc90** [comment]
Domain adoptation의 경우 vocap 문제가 생길수 있어서 Token을 확장해야 할수도 있다. 

한국어 확장 케이스
https://huggingface.co/yanolja/EEVE-Korean-Instruct-10.8B-v1.0
