### ISSUE TITLE
LoRA로 학습한건지 Full Finetuning으로 학습한건지?

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#19]
그러고보니 Training Setup은 논문에서 분석을 안했네요

https://github.com/ShishirPatil/gorilla/blob/main/raft/azure-ai-studio-ft/howto.md

**Comment by jaehc90** [comment]
Domain Adoptation 인 경우 Full fine tuning vs LORA FT 이 더 괜찮은가? 

=> Full Fine Tuning에 더 많은 데이터가 필요한 거 같다. 
=> 지금 논문의 데이터 사이즈가 작다 => LORA일거 같다?
