### ISSUE TITLE
reference for "RAG를 할때 LLM parameter에는 무슨 일이 일어날까"

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#20]
[RALM: RAG (LLM with retrieval) 결합 방식에 대한 이론적 토대! | TACL 2023 | 김재희
](https://www.youtube.com/watch?v=eYSMUqtljSI)

**Comment by ZiminPark** [comment]
#24

**Comment by ZiminPark** [comment]
#25

**Comment by realsigridjin** [comment]
이전에 ssl 발제에서 나왔던 내용을 바탕으로 정리했던 내용입니다.
https://jypthemiracle.notion.site/In-Context-Retrieval-Augmented-Language-Models-RALM-614b29da91bf42d695957a67d14610d9

**Comment by ZiminPark** [comment]
[Knowledge Conflicts for LLMs: A Survey](https://arxiv.org/pdf/2403.08319)
![image](https://github.com/user-attachments/assets/fa95d7f7-3db3-4725-81ba-aacaecd81fcb)
