### ISSUE TITLE
이해하기- Finding 1: Language models minimally use parametric memory in the presence of context

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#21]
1. Causal Tracing 방법 & IE(Indirect Effect) 수치 의의 이해하기
2. FST(First Subject Token), LST(Last Subject Token), LT(Last Token) 이 뭘 지칭하는지 이해하기
3. 실험 결과 그래프 해석하기
<img width="369" alt="image" src="https://github.com/user-attachments/assets/cd4c028a-7bb4-424a-84af-4d4db113bbe1">

<img width="687" alt="image" src="https://github.com/user-attachments/assets/26bda328-59c2-402b-88a5-dd3f6de8d3bb">

**Comment by realsigridjin** [comment]
left: RAG 사용시. LST, LT에서 활성화 조금
right: vanilla (non-RAG), LST에서 강한 활성화가 관찰됨

llama-2, phi-2에서 동일 하지만 의미 없음. shortcut = context
