### ISSUE TITLE
QA 말고 Spreadsheet에 어떤 Task/ UseCase가 LLM이 필요할지?

### ISSUE THREAD

**Issue by ZiminPark** [ZiminPark/coffee-augmented-rag#27]
필요하다면 그 Task도 이런 Encoding 이 필요할지?

**Comment by oneonlee** [comment]
VScode의 Copilot처럼 데이터를 자동완성시켜주는 실용적인 task에도 사용될 수 있지 않을까 생각합니다.

**Comment by ZiminPark** [comment]
Tabluar, DB 로 확장할 수도.
Spreadsheet에도 SQL 날릴 수도?

**Comment by ZiminPark** [comment]
Modify, 깔끔하게 정리, Column 추가, Pivot

**Comment by ZiminPark** [comment]
업무 중에 엑셀 쓰는 것 생각해보면 큰 테이블로부터 summary해서 잘 정리된 작은 테이블 만들어줄 수 있으면 유용할 것 같습니다
