### ISSUE TITLE
(번외?) 원본 table과 행열을 transpose한 table 중 어떤 table이 성능이 괜찮을까?

### ISSUE THREAD

**Issue by oneonlee** [ZiminPark/coffee-augmented-rag#32]
llm은 sequential하게 데이터를 읽을텐데 행열의 transpose 유무에 따라 성능이 달라질 것 같다.
이 부분에 대한 추가 탐구도 좋을 것 같다.

**Comment by ZiminPark** [comment]
+ head에 depth가 있을 때 성능이 괜찮을까?

**Comment by ZiminPark** [comment]
+ Pivot Table

**Comment by ZiminPark** [comment]
라인수가 크면 transpose하면 용량도 커지고 가독성이 떨어져서 잘 쓰지 않습니다
아 db 관점에서요
