### ISSUE TITLE
using a logit bias of 100 to force a yes/no decision

### ISSUE THREAD

**Issue by haconedu** [ZiminPark/coffee-augmented-rag#35]
구체적으로 어떻게 한다는 의미일지?

**Comment by ZiminPark** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/7379f7ba-63bd-46ad-a82b-4b5667b5e4fb">

**Comment by ZiminPark** [comment]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/81e01ead-5185-4be7-b704-ef0616f75d65">

**Comment by ZiminPark** [comment]
MMLU

![image](https://github.com/user-attachments/assets/d862d69f-1c4c-4a3a-a4d1-362b9c0eb70a)

**Comment by ZiminPark** [comment]
API Spec
https://platform.openai.com/docs/api-reference/chat/create#chat-create-logit_bias

결과를 항상 나오게하려면 100으로 셋팅
