### ISSUE TITLE
Community summaries are randomly shuffled 는 하나의 커뮤니티 요약문 내에서 문장별로 여러 청크에 나눠버린다는 의미일지?

### ISSUE THREAD

**Issue by haconedu** [ZiminPark/coffee-augmented-rag#38]
Prepare community summaries. Community summaries are randomly shuffled and divided into chunks of pre-specified token size. This ensures relevant information is distributed across chunks, rather than concentrated (and potentially lost) in a single context window.

**Comment by ZiminPark** [comment]
![image](https://github.com/user-attachments/assets/ec14535f-977c-43af-b8ac-087284827436)
